version: '3.7'
services:
  client:
    build: client
    image: huutien120802/client-ai-camera
    restart: unless-stopped
    container_name: client-container
    networks:
      - apinetwork
    ports:
      - 3000:3000

  api_server:
    build: server
    image: huutien120802/server-ai-camera
    ports:
      - 3009:3009
    restart: unless-stopped
    container_name: api-server-container
    environment:
      - PORT=3009
      - MONGO_URL=mongodb://mongo_db:27017/test
    depends_on:
      - mongo_db
    networks:
      - apinetwork

  mongo_db:
    image: mongo
    restart: unless-stopped
    container_name: mongo-container
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - apinetwork

  mongo_seed:
    build: mongodb
    image: huutien120802/mongo_seed-ai-camera
    container_name: mongo-seed-container
    depends_on:
      - mongo_db
    networks:
      - apinetwork

  nginx:
    build: nginx
    image: huutien120802/nginx-ai-camera
    restart: unless-stopped
    container_name: nginx-container
    ports:
      - 81:80
    networks:
      - apinetwork
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    depends_on:
      - client

networks:
  apinetwork:
    driver: bridge
