version: '3.7'
services:
  client:
    build: client
    restart: unless-stopped
    container_name: client-container

  server:
    build: server
    restart: unless-stopped
    container_name: server-container
    ports:
      - 3009:3009

  mongo_db:
    image: mongo:lastest
    restart: always
    container_name: mongo_db-container
    ports:
      - 27017:27017

  nginx:
    build: nginx
    restart: unless-stopped
    container_name: nginx-container
    ports:
      - 81:80
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - CLIENT_HOST=client
      - CLIENT_PORT=3000