export const GET_ALL_STATISTICS = 'GET_ALL_STATISTICS';
export const GET_ALL_STATISTICS_SUCCESS = 'GET_ALL_STATISTICS_SUCCESS';
export const GET_ALL_STATISTICS_FAILED = 'GET_ALL_STATISTICS_FAILED';

export const REMOVE_STATISTICS = 'REMOVE_STATISTICS';
export const REMOVE_STATISTICS_SUCCESS = 'REMOVE_STATISTICS_SUCCESS';
export const REMOVE_STATISTICS_FAILED = 'REMOVE_STATISTICS_FAILED';

export const MARK_AS_READED_STATISTICS = 'MARK_AS_READED_STATISTICS';
export const MARK_AS_READED_STATISTICS_SUCCESS = 'MARK_AS_READED_STATISTICS_SUCCESS';
export const MARK_AS_READED_STATISTICS_FAILED = 'MARK_AS_READED_STATISTICS_FAILED';
