export const GET_ALL_WARNINGS = 'GET_ALL_WARNINGS';
export const GET_ALL_WARNINGS_SUCCESS = 'GET_ALL_WARNINGS_SUCCESS';
export const GET_ALL_WARNINGS_FAILED = 'GET_ALL_WARNINGS_FAILED';

export const REMOVE_WARNINGS = 'REMOVE_WARNINGS';
export const REMOVE_WARNINGS_SUCCESS = 'REMOVE_WARNINGS_SUCCESS';
export const REMOVE_WARNINGS_FAILED = 'REMOVE_WARNINGS_FAILED';

export const ADD_WARNING = 'ADD_WARNING';
export const ADD_WARNING_SUCCESS = 'ADD_WARNING_SUCCESS';
export const ADD_WARNING_FAILED = 'ADD_WARNING_FAILED';

export const MARK_AS_READED_WARNINGS = 'MARK_AS_READED_WARNINGS';
export const MARK_AS_READED_WARNINGS_SUCCESS = 'MARK_AS_READED_WARNINGS_SUCCESS';
export const MARK_AS_READED_WARNINGS_FAILED = 'MARK_AS_READED_WARNINGS_FAILED';
