export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';

export const GET_COUNT_PROFILE = 'GET_COUNT_PROFILE';
export const GET_COUNT_PROFILE_SUCCESS = 'GET_COUNT_PROFILE_SUCCESS';
export const GET_COUNT_PROFILE_FAILED = 'COUNT_PROFILE_FAILED';
