export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_FAILED = 'GET_MY_PROFILE_FAILED';

export const LOGOUT = 'LOGOUT';
